
language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1

matrix:
    include:
        - php: hhvm
          dist: trusty
          sudo: required

install:
    - composer self-update
    - composer install

script:
    - vendor/bin/phpunit
